name: Cli Core Tests
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-x64
    strategy:
      fail-fast: false
      matrix:
        node-version: [lts/*, 22.x, 20.x]
    steps:
      - name: Checkout cli core repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - run: make install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run tests
        run: make test
      - name: SonarCloud Scan
        uses:  SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f #v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  notify-complete-fail:
    if: ${{ failure() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
    needs: [ test ]
    name: Notify Test Failed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_WEBHOOK: ${{ secrets.ALERT_SLACK_WEB_HOOK }}
          SLACK_COLOR: 'danger'
          SLACK_USERNAME: CLI Github Actions
          SLACK_MSG_AUTHOR: twilio-dx
          SLACK_ICON_EMOJI: ':github:'
          SLACK_TITLE: "Twilio Cli Core"
          SLACK_MESSAGE: 'Cli core tests failed'
          MSG_MINIMAL: actions url
          SLACK_FOOTER: Posted automatically using GitHub Actions
